name: jaspr_app_write_site
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_appwrite: ^12.1.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  jaspr: ^0.16.0
  jaspr_flutter_embed: ^0.4.0
  jaspr_riverpod: ^0.3.15
  jaspr_router: ^0.6.0
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  jaspr_builder: ^0.16.0
  jaspr_lints: ^0.1.2
  jaspr_web_compilers: ^4.0.10+1

jaspr:
  mode: server

flutter:
  uses-material-design: true
